apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: default
spec:
  rules:
  - host: echoserver.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 80
