# ###################################
# Common setup for all ec2 instances
# ###################################
---
# Create directories
- name: create directories
  file: name={{item}} state=directory
  with_items:
  - /opt/bin/
  - /etc/flannel/
  - /etc/systemd/system/locksmithd.service.d/
  - /etc/systemd/system/flanneld.service.d/
  - /etc/systemd/system/docker.service.d/

# bootstraping with python
- name: "Check if need to install python"
  raw: "stat /opt/python/.bootstrapped"
  register: need_bootstrap
  ignore_errors: True
  changed_when: false

- name: "scp python tar file"
  become: no
  local_action : "command scp {{playbook_dir}}/{{role_dir}}/files/python/pypy.tar.bz2 core@{{inventory_hostname}}:/tmp/pypy.tar.bz2"
  when: need_bootstrap | failed

- name: "scp bootstrap.sh"
  become: no
  local_action : "command scp {{playbook_dir}}/{{role_dir}}/files/python/bootstrap.sh core@{{inventory_hostname}}:/tmp/bootstrap.sh"
  when: need_bootstrap | failed

- name: "run bootstrap"
  become: yes
  raw: "PYTHON_VERSION={{python_version}} PYPY_VERSION={{pypy_version}} sh /tmp/bootstrap.sh"
  when: need_bootstrap | failed

- name: "Set bootstrapped file"
  file:
    path: /opt/python/.bootstrapped
    state: touch
  changed_when: false

# Upload configs

- name: "upload docker-login-gen"
  copy:
    src: "{{playbook_dir}}/{{role_dir}}/files/docker-login-gen"
    dest: "/opt/bin/docker-login-gen"
    owner: root
    mode: 0755

- name: "uplaod flanneld, locksmithd and docker configs"
  file:
    src: "{{playbook_dir}}/{{role_dir}}/{{item.name}}"
    dest: "{{item.dest}}/{{item.name}}"
    state: file
    owner: root
    mode: 0644
  with_items:
    - { name: "01-wait-for-certs.conf", dest: "/etc/systemd/system/locksmithd.service.d"}
    - { name: "50-network-config.conf", dest: "/etc/systemd/system/flanneld.service.d"}
    - { name: "40-flannel.conf", dest: "/etc/systemd/system/docker.service.d"}

# Upload services
- name: "Upload services"
  file:
    src: "{{playbook_dir}}/{{role_dir}}/files/docker-ecr-cfg.service"
    dest: "/etc/systemd/system/docker-ecr-cfg.service"
    owner: root
    mode: 0644

- name: "Upload templated prefetch-flannel.service"
  template:
    src: "{{playbook_dir}}/{{role_dir}}/files/templates/prefetch-flannel.service"
    dest: "/etc/systemd/system/prefetch-flannel.service"
    owner: root
    mode: 0644

- name: "upload templated prefetch-docker-hyperkube.service"
  template:
    src:
      "{{playbook_dir}}/{{role_dir}}/files/templates/prefetch-docker-hyperkube.service"
    dest: "/etc/systemd/system/prefetch-docker-hyperkube.service"
    owner: root
    mode: 0644
