apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
imagePullSecrets:
- name: aws-ecr-cn-north-1

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
