#cloud-config
coreos:
  etcd2:
    advertise-client-urls: https://$private_ipv4:2379
    listen-client-urls: https://0.0.0.0:2379
    client-cert-auth: true
    trusted-ca-file: /etc/kubernetes/ssl/ca.pem
    cert-file: /etc/kubernetes/ssl/etcd.pem
    key-file: /etc/kubernetes/ssl/etcd-key.pem

  flannel:
    interface: $private_ipv4
    etcd_cafile: /etc/kubernetes/ssl/ca.pem
    etcd_certfile: /etc/kubernetes/ssl/etcd.pem
    etcd_keyfile: /etc/kubernetes/ssl/etcd-key.pem
    etcd_endpoints: https://$private_ipv4:2379

  locksmith:
    endpoint: https://$private_ipv4:2379
    etcd_cafile: /etc/kubernetes/ssl/ca.pem
    etcd_certfile: /etc/kubernetes/ssl/etcd.pem
    etcd_keyfile: /etc/kubernetes/ssl/etcd-key.pem

  update:
    reboot-strategy: etcd-lock

  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 01-wait-for-certs.conf
          content: |
            [Unit]
            ConditionFileNotEmpty=/etc/kubernetes/ssl/ca.pem
            ConditionFileNotEmpty=/etc/kubernetes/ssl/etcd.pem
            ConditionFileNotEmpty=/etc/kubernetes/ssl/etcd-key.pem
            [Service]
            EnvironmentFile=/etc/environment
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            ConditionFileNotEmpty=/etc/kubernetes/ssl/ca.pem
            ConditionFileNotEmpty=/etc/kubernetes/ssl/etcd.pem
            ConditionFileNotEmpty=/etc/kubernetes/ssl/etcd-key.pem
            After=prefetch-flannel.service
            Requires=prefetch-flannel.service
            Description=Prefetch flannel
            [Service]
            EnvironmentFile=/etc/environment
            Environment="ETCD_SSL_DIR=/etc/kubernetes/ssl"
            ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config \
              '{ "Network": "${ POD_NETWORK }", "Backend": { "Type": "vxlan" } }'
            Restart=always
            RestartSec=10
    - name: locksmithd.service
      command: start
      drop-ins:
        - name: 01-wait-for-certs.conf
          content: |
            [Unit]
            ConditionFileNotEmpty=/etc/kubernetes/ssl/ca.pem
            ConditionFileNotEmpty=/etc/kubernetes/ssl/etcd.pem
            ConditionFileNotEmpty=/etc/kubernetes/ssl/etcd-key.pem
            [Service]
            EnvironmentFile=/etc/environment
    - name: docker.service
      command: start
      drop-ins:
        - name: 40-flannel.conf
          content: |
            [Unit]
            After=flanneld.service
            Requires=flanneld.service
            [Service]
            Restart=always
            RestartSec=10
