apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ecr-dockercfg-refresh
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ecr-dockercfg-refresh
  template:
    metadata:
      labels:
        run: ecr-dockercfg-refresh
    spec:
      serviceAccountName: ecr-dockercfg-refresh
      containers:
      - image: daocloud.io/mixslice/ecr-dockercfg-refresh:master-0c6329f
        name: ecr-dockercfg-refresh
        envFrom:
        - configMapRef:
            name: ecr-dockercfg-refresh
      restartPolicy: Always
