apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-dockercfg-refresh
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ecr-dockercfg-refresh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: token-refresh
subjects:
- kind: ServiceAccount
  name: ecr-dockercfg-refresh
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: token-refresh
  labels:
    app: token-refresh
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - secrets
  verbs:
  - create
  - get
  - watch
  - list
  - update
  - patch
