---
##############################
# Setup K8s components
##############################

- hosts: all
  become: yes
  gather_facts: false
  roles:
    - common

- hosts: k8s-masters
  become: yes
  roles:
    - master

- hosts: k8s-workers
  become: yes
  vars: {
    NODE_LABELS: "{{worker_node_labels}}"
  }
  roles:
    - worker


- hosts: k8s-edges
  become: yes
  vars: {
    NODE_LABELS: "{{edge_node_labels}}"
  }
  roles:
    - worker

##############################
# Setup kubectl
##############################
# - hosts: localhost
#   tasks:
#     - name: test
#       raw: "echo a"
#
# - hosts: localhost
#   roles:
#     - kubecontrol
