---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    run: jenkins
spec:
  selector:
    run: jenkins
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 50000
    targetPort: 50000
    name: slave
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress
  namespace: default
imagePullSecrets:
- name: aws-ecr-cn-north-1
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingress
subjects:
  - kind: ServiceAccount
    name: ingress
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
