---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      securityContext:
        fsGroup: 99
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: ingress
      containers:
        - name: jenkins
          image: 493490470276.dkr.ecr.cn-north-1.amazonaws.com.cn/jenkins:lts
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          ports:
            - containerPort: 8080
            - containerPort: 50000
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      # volumes:
      # - hostPath:
      #     path: /etc/kubernetes/jenkins
      #   name: jenkins-home
