---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  labels:
    name: jenkins-slave
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: jenkins-slave
      image: daocloud.io/mixslice/jenkins-slave-custom:latest
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      env:
        - name: JENKINS_URL
          value: http://jenkins.mixslice.com
        - name: JENKINS_TUNNEL
          value: jenkins-tunnel.mixslice.com:80
      args:
        - 59d64d145d48ba315956c1169ff5d80dd6198fb1bfff9d96e0de459c3818c5b3
        - jenkins-slave-01
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
